"""Generate a small TypeScript contract surface from the local FastAPI OpenAPI schema.

This intentionally avoids a network dependency or a second hand-written DTO tree. The
generated file is a compile-time boundary only; runtime requests remain in apps/web/src/api.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "apps" / "web" / "src" / "api" / "openapi.generated.ts"


def ref_name(schema: dict[str, Any]) -> str | None:
    ref = schema.get("$ref")
    return ref.rsplit("/", 1)[-1] if isinstance(ref, str) else None


def ts_type(schema: dict[str, Any] | None) -> str:
    if not schema:
        return "unknown"
    reference = ref_name(schema)
    if reference:
        return reference
    if "anyOf" in schema:
        return " | ".join(ts_type(item) for item in schema["anyOf"])
    if "oneOf" in schema:
        return " | ".join(ts_type(item) for item in schema["oneOf"])
    if "allOf" in schema:
        return " & ".join(ts_type(item) for item in schema["allOf"])
    kind = schema.get("type")
    if kind == "array":
        return f"Array<{ts_type(schema.get('items'))}>"
    if kind == "object":
        properties = schema.get("properties")
        if not properties:
            return "Record<string, unknown>"
        return "Record<string, unknown>"
    if kind in {"integer", "number"}:
        return "number"
    if kind == "boolean":
        return "boolean"
    if kind == "null":
        return "null"
    if kind == "string":
        enum = schema.get("enum")
        if enum:
            return " | ".join(json.dumps(value, ensure_ascii=False) for value in enum)
        return "string"
    return "unknown"


def interface(name: str, schema: dict[str, Any]) -> str:
    properties = schema.get("properties", {})
    required = set(schema.get("required", []))
    lines = [f"export interface {name} {{"]
    for field, value in properties.items():
        optional = "" if field in required else "?"
        lines.append(f"  {field}{optional}: {ts_type(value)}")
    lines.append("}")
    return "\n".join(lines)


def main() -> None:
    from apps.api.main import create_app

    schemas = create_app().openapi().get("components", {}).get("schemas", {})
    content = [
        "// AUTO-GENERATED by scripts/generate-web-openapi.py; do not edit manually.",
        "// Source: apps.api.main:create_app().openapi()",
        "",
    ]
    for name in sorted(schemas):
        schema = schemas[name]
        if schema.get("type") == "object":
            content.append(interface(name, schema))
        else:
            content.append(f"export type {name} = {ts_type(schema)}")
        content.append("")
    OUTPUT.write_text("\n".join(content), encoding="utf-8")
    print(f"generated {OUTPUT} ({len(schemas)} schemas)")


if __name__ == "__main__":
    main()
