// AUTO-GENERATED by scripts/generate-web-openapi.py; do not edit manually.
// Source: apps.api.main:create_app().openapi()

export interface AnswerResponse {
  conversation_id: string
  user_message: MessageResponse
  assistant_message: MessageResponse
  answer: string
  citations?: Array<CitationResponse>
  evidence_available: boolean
  source: string
  limitations?: Array<string>
  boundary: BoundaryResponse
  summary_version?: number
}

export interface AssetResponse {
  asset_id: string
  role: string
  mime: string
  size_bytes: number
  sha256: string
  download_url?: string | null
}

export interface BoundaryResponse {
  workspace_id: string
  job_id?: string | null
  conversation_id: string
  allowed_sources?: Array<string>
  limitations?: Array<string>
}

export interface CitationResponse {
  evidence_id?: string | null
  citation_id?: string | null
  source_ref?: string | null
  document_id?: string | null
  chunk_id?: string | null
  page?: number | null
  version?: string | null
  fact?: string | null
  limitations?: Array<string>
}

export interface ConversationRequest {
  title: string
  job_id?: string | null
}

export interface ConversationResponse {
  conversation_id: string
  workspace_id: string
  job_id?: string | null
  title: string
  summary_version?: number
  summary?: Record<string, unknown> | null
  created_at?: string | null
  updated_at?: string | null
}

export interface ConversationSummaryResponse {
  conversation_id: string
  version: number
  summary: string
  summary_hash: string
  updated_at: string
  source_message_start?: string | null
  source_message_end?: string | null
  boundary: BoundaryResponse
}

export interface CreateJobRequest {
  mode: "image" | "video" | "structured"
  goal?: string
  metadata?: Record<string, unknown>
}

export interface FeedbackRequest {
  decision: "APPROVED" | "REJECTED" | "MODIFIED" | "MATERIALS_REQUESTED"
  reason: string
  original_observation?: Record<string, unknown>
  revised_observation?: Record<string, unknown> | null
  evidence_ids?: Array<string>
}

export interface HTTPValidationError {
  detail?: Array<ValidationError>
}

export interface JobResponse {
  job_id: string
  workspace_id: string
  mode: string
  status: string
  progress: number
  created_at?: string | null
  updated_at?: string | null
  error_code?: string | null
  error_message?: string | null
}

export interface KnowledgeDocumentRequest {
  source_id: string
  source: string
  title: string
  author_or_organization: string
  license: string
  authorization_status: string
  sha256: string
  visibility_scope?: string
  version?: string
  status?: string
}

export interface LoginRequest {
  email: string
  password: string
}

export interface LoginResponse {
  access_token: string
  token_type?: string
  user_id: string
  workspace_id?: string | null
}

export interface MessageRequest {
  content: string
}

export interface MessageResponse {
  message_id: string
  conversation_id: string
  role: "user" | "assistant" | "system"
  content: string
  citations?: Array<CitationResponse>
  evidence_available?: boolean
  source?: string | null
  limitations?: Array<string>
  boundary?: Record<string, unknown>
  created_at?: string | null
}

export interface ReviewDecisionRequest {
  decision: "APPROVED" | "REJECTED" | "MODIFIED" | "MATERIALS_REQUESTED"
  note?: string
  revised_observation?: Record<string, unknown> | null
}

export interface ReviewItemResponse {
  review_id: string
  job_id: string
  status: string
  decision?: string | null
  reason: string
  reviewer_id?: string | null
  revision: number
  original_observation?: Record<string, unknown>
  revised_observation?: Record<string, unknown> | null
  evidence_ids?: Array<string>
  created_at?: string | null
  decided_at?: string | null
}

export interface ReviewStatsResponse {
  total: number
  pending: number
  decided: number
  by_decision?: Record<string, unknown>
}

export interface StartResponse {
  job_id: string
  run_id: string
  job_status: string
  run_status: string
  task_id?: string | null
}

export interface UploadCompleteRequest {
  expected_size_bytes: number
  expected_sha256: string
}

export interface UploadInitRequest {
  expected_mime: string
  max_size_bytes: number
  role?: string
}

export interface UploadInitResponse {
  upload_id: string
  object_key: string
  upload_url: string
  expected_mime: string
  max_size_bytes: number
  expires_at: string
}

export interface ValidationError {
  loc: Array<string | number>
  msg: string
  type: string
  input?: unknown
  ctx?: Record<string, unknown>
}
