// AUTO-GENERATED by scripts/generate-web-openapi.py; do not edit manually.
// Source: apps.api.main:create_app().openapi()

export interface AssetResponse {
  asset_id: string
  role: string
  mime: string
  size_bytes: number
  sha256: string
  download_url?: string | null
}

export interface ConversationRequest {
  title: string
  job_id?: string | null
}

export interface CreateJobRequest {
  mode: "image" | "video" | "structured"
  goal?: string
  metadata?: Record<string, unknown>
}

export interface HTTPValidationError {
  detail?: Array<ValidationError>
}

export interface JobResponse {
  job_id: string
  workspace_id: string
  mode: string
  status: string
  progress: number
  created_at?: string | null
  updated_at?: string | null
  error_code?: string | null
  error_message?: string | null
}

export interface KnowledgeDocumentRequest {
  source_id: string
  source: string
  title: string
  author_or_organization: string
  license: string
  authorization_status: string
  sha256: string
  visibility_scope?: string
  version?: string
  status?: string
}

export interface LoginRequest {
  email: string
  password: string
}

export interface LoginResponse {
  access_token: string
  token_type?: string
  user_id: string
  workspace_id?: string | null
}

export interface MessageRequest {
  content: string
}

export interface ReviewDecisionRequest {
  decision: "APPROVED" | "REJECTED" | "MODIFIED" | "MATERIALS_REQUESTED"
  note?: string
  revised_observation?: Record<string, unknown> | null
}

export interface StartResponse {
  job_id: string
  run_id: string
  job_status: string
  run_status: string
  task_id?: string | null
}

export interface UploadCompleteRequest {
  expected_size_bytes: number
  expected_sha256: string
}

export interface UploadInitRequest {
  expected_mime: string
  max_size_bytes: number
  role?: string
}

export interface UploadInitResponse {
  upload_id: string
  object_key: string
  upload_url: string
  expected_mime: string
  max_size_bytes: number
  expires_at: string
}

export interface ValidationError {
  loc: Array<string | number>
  msg: string
  type: string
  input?: unknown
  ctx?: Record<string, unknown>
}
